# Spring Boot configuration
spring:
  application:
    name: App
  profiles:
    active: development

  # Database configuration
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/automobiles
    username: postgres
    password: postgres

  # JPA (Java Persistence API) configuration
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Security configuration for OAuth2
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8180/realms/automobile-realm

  # JMS (Java Messaging Service) configuration
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: tcp://localhost:61616

jwt:
  converter:
    principle-attribute: preferred_username

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /demo

# Logging configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.springframework.security: debug
    org.springframework.security.oauth2: debug
    com.kaluzny.demo: debug

# Springdoc configuration for Swagger UI
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs.yaml

# Spring Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
